### ISSUE TITLE
[RFC0030] Add Support for File based Service Binding Information

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/community#901]
This is a tracking issue for the implementation of https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0030-add-support-for-file-based-service-binding.md

**Delivered with**:
CF-Deployment version: [v48.5.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v48.5.0)
CLI version: n/a
CF Docs: https://docs.cloudfoundry.org/devguide/services/application-binding.html, https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html

### Tasks
- [x]  https://github.com/cloudfoundry/diego-release/pull/942
- [x]  https://github.com/cloudfoundry/bbs/pull/100
- [x] https://github.com/cloudfoundry/rep/pull/56
- [x] https://github.com/cloudfoundry/executor/pull/100
- [x] https://github.com/cloudfoundry/cloud_controller_ng/pull/3996
- [x] https://github.com/cloudfoundry/cloud_controller_ng/pull/3997
- [x] https://github.com/cloudfoundry/cloud_controller_ng/pull/4026
- [x] https://github.com/cloudfoundry/cloud_controller_ng/issues/4036
- [x] https://github.com/cloudfoundry/cloud_controller_ng/pull/4235
- [x] https://github.com/cloudfoundry/cf-acceptance-tests/pull/1374
- [x] https://github.com/cloudfoundry/cf-acceptance-tests/pull/1384
- [x] https://github.com/cloudfoundry/cf-acceptance-tests/pull/1437
- [x] https://github.com/cloudfoundry/docs-dev-guide/pull/551

**Comment by dimitardimitrov13** [comment]
Hello there, here are the 4 PRs within diego-release, bbs, rep, and executor. They are needed for RFC-0030.

1. Diego Release: https://github.com/cloudfoundry/diego-release/pull/942
2. BBS: https://github.com/cloudfoundry/bbs/pull/100
3. REP: https://github.com/cloudfoundry/rep/pull/56
4. Executor: https://github.com/cloudfoundry/executor/pull/100

**Comment by beyhan** [comment]
@dimitardimitrov13 thanks for the update!

**Comment by dimitardimitrov13** [comment]
@beyhan, thank you.

**Comment by ameowlia** [comment]
🎉  Hi @dimitardimitrov13 , Excellent work so far!

Please ping me on slack (too easy to miss github notifications with 100+ repos 🫠 ) when the CAPI PRs are done and we can test this end-to-end. At that point I will assign a Diego reviewer.

**Comment by dimitardimitrov13** [comment]
Hello Amelia,

Thanks for your message. Unfortunately, we do not have a straightforward way to test this end-to-end. During the implementation stage, I used a custom build of cfdot and a mocked code inside the BBS to simulate this. The code was cleaned up from the BBS before the PR. It seems we will need to wait for the CAPI team.

Best regards,
Dimitar

**Comment by PlamenDoychev** [comment]
Hi @ameowlia,

Just in case you haven't seen the input from @dimitardimitrov13 above.
Should we wait for CAPI then?

**Comment by beyhan** [comment]
>Should we wait for CAPI then?

This is what I read in the comment above https://github.com/cloudfoundry/community/issues/901#issuecomment-2271522114

**Comment by ameowlia** [comment]
Yes, I want to wait to merge until we can test it end-to-end. That way we can make sure everything works all the way through and we don't have to worry about breaking changes if part of it is released, but then it ends up things need to change to work with CAPI.

**Comment by philippthun** [comment]
@beyhan, @dimitardimitrov13: As I've started to implement the CAPI part of this, I came across the changed BBS interface. I suggest that we adapt `Files` to `File` as this entity represents a single file. This would be inline with e.g. `EnvironmentVariable`.

When already changing the BBS interface, I would also like to discuss, if we can adapt the attributes. Currently they are named `name` and `value`. I would find `path` and `content` more intuitive. `path` due to the fact that we always specify files within a parent folder named after the binding, so the value would be something like `my-binding/instance_name`. Maybe `relative_path` would be even better...

**Comment by philippthun** [comment]
And another topic to discuss is the usage of non-Ascii characters. Today you can do the following:

```
cf create-user-provided-service 💥 -p '{"💣":"🔥"}'
```

The env var looks then as follows:
```
VCAP_SERVICES: {
  "user-provided": [
    {
      "binding_guid": "1389756a-016a-4dac-80c6-e0a71b80c8e3",
      "binding_name": null,
      "credentials": {
        "💣": "🔥"
      },
      "instance_guid": "ed10c46a-3d75-4832-b53b-294ac7cfae09",
      "instance_name": "💥",
      "label": "user-provided",
      "name": "💥",
      "syslog_drain_url": null,
      "tags": [],
      "volume_mounts": []
    }
  ]
}
```

With file-based service bindings this would result in a file `$SERVICE_BINDING_ROOT/💥/💣`. Besides contradicting the **Service Binding for Kubernetes** spec (_Binding names MUST match [a-z0-9\-\.]{1,253}_ / _The name of a binding entry file name SHOULD match [a-z0-9\-\.]{1,253}_), I'm wondering if this would work. What are the specs for directory and file names in the `tmpfs` file system?

**Comment by philippthun** [comment]
There's also a possible name conflict. The RFC states that the directory should be named after the service binding. I guess that this refers to the `name` attribute, which is either `binding_name` or (if the first one is not set) `instance_name`. Whereas it is not possible to create two service instances with the same name or two service bindings with the same name, it is possible to create a first service binding with the name `foobar` from an arbitrary service instance and another service binding without a name from a service instance called `foobar`. This would mean that both binding entries end up with `name=foobar`. When mapping this to file-based service bindings, there would be a conflict...

**Comment by beyhan** [comment]
> @beyhan, @dimitardimitrov13: As I've started to implement the CAPI part of this, I came across the changed BBS interface. I suggest that we adapt `Files` to `File` as this entity represents a single file. This would be inline with e.g. `EnvironmentVariable`.
> 
> When already changing the BBS interface, I would also like to discuss, if we can adapt the attributes. Currently they are named `name` and `value`. I would find `path` and `content` more intuitive. `path` due to the fact that we always specify files within a parent folder named after the binding, so the value would be something like `my-binding/instance_name`. Maybe `relative_path` would be even better...

Referring to a discussion (https://github.com/cloudfoundry/community/pull/994#discussion_r1802331359) in an RFC willing to build on top of this I would say that we should go for the suggested name there change `ServiceBindingFiles` to `VolumeMountedFiles` and `Files` to `File`. The suggestion to change `name` to `path` and `value` to `content` sounds reasonable to me. If everyone is OK with this I will update the RFC. @ameowlia , @ChrisMcGowan , @rkoster , @stephanme, @Gerg, @PlamenDoychev any thoughts on this?

**Comment by dimitardimitrov13** [comment]
Hello,

I agree that good naming conventions should always be chosen. Since we have already changed it once (as requested by Stefan Merker), it could be done again. Regarding the other comments, I'll take a look next week and get back to you with answers.

Best regards,
Dimitar

**Comment by beyhan** [comment]
> And another topic to discuss is the usage of non-Ascii characters. Today you can do the following:
> 
> ```
> cf create-user-provided-service 💥 -p '{"💣":"🔥"}'
> ```
> 
> The env var looks then as follows:
> 
> ```
> VCAP_SERVICES: {
>   "user-provided": [
>     {
>       "binding_guid": "1389756a-016a-4dac-80c6-e0a71b80c8e3",
>       "binding_name": null,
>       "credentials": {
>         "💣": "🔥"
>       },
>       "instance_guid": "ed10c46a-3d75-4832-b53b-294ac7cfae09",
>       "instance_name": "💥",
>       "label": "user-provided",
>       "name": "💥",
>       "syslog_drain_url": null,
>       "tags": [],
>       "volume_mounts": []
>     }
>   ]
> }
> ```
> 
> With file-based service bindings this would result in a file `$SERVICE_BINDING_ROOT/💥/💣`. Besides contradicting the **Service Binding for Kubernetes** spec (_Binding names MUST match [a-z0-9-.]{1,253}_ / _The name of a binding entry file name SHOULD match [a-z0-9-.]{1,253}_), I'm wondering if this would work. What are the specs for directory and file names in the `tmpfs` file system?

The RFC defines that we should support the K8s service binding spec naming conventions in https://github.com/cloudfoundry/community/blob/411475b4587238e1fe531fc8b2647c96fdbcb9a2/toc/rfc/rfc-0030-add-support-for-file-based-service-binding.md?plain=1#L36. I would suggest that the CC validates this and returns an error if it is not the case. This will be a breaking change for users' with naming which is not supported by the K8s spec but the users must anyway opt-in here and in this case it should be fine. I couldn't find any specific rules for `tmpfs` file system but most probably it supports the same as Linux OS and according to the rules listed in https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations K8s naming specification should be fine.  Any thoughts on this @ameowlia , @ChrisMcGowan , @rkoster , @stephanme, @Gerg?

**Comment by beyhan** [comment]
> There's also a possible name conflict. The RFC states that the directory should be named after the service binding. I guess that this refers to the `name` attribute, which is either `binding_name` or (if the first one is not set) `instance_name`. Whereas it is not possible to create two service instances with the same name or two service bindings with the same name, it is possible to create a first service binding with the name `foobar` from an arbitrary service instance and another service binding without a name from a service instance called `foobar`. This would mean that both binding entries end up with `name=foobar`. When mapping this to file-based service bindings, there would be a conflict...

In the [K8s spec](https://servicebinding.io/spec/core/1.1.0/#workload-projection) is stated that:
```
Users SHOULD ensure each binding has a unique name. The behavior for name collisions is undefined. Implementations MAY attempt a good faith check for collisions to provide a meaningful error message.
```
I think we should make sure that this conflict results in an error like with the name in the previous comment. It also sounds as a missing validation in the current behaviour of CC. Do we have any other alternative?

**Comment by philippthun** [comment]
> > And another topic to discuss is the usage of non-Ascii characters. [...]
> 
> I would suggest that the CC validates this and returns an error if it is not the case. [...]

Okay, I've implemented the **MUST** requirement for service binding names. But what about the **SHOULD** requirement for binding entry file names?

We would already violate this by using the defined `VCAP_SERVICES` attributes as file names, e.g. `binding_guid`, as the underscore is not allowed by the k8s spec. Should we:
1. translate underscores to dashes (e.g. `binding_guid` to `binding-guid`) and then strictly enforce the k8s spec?
2. add the underscore to the list of allowed characters and enforce this slightly modified spec?
3. simply ignore this **SHOULD** requirement...

I would prefer one of the first two options.

**Comment by philippthun** [comment]
> > There's also a possible name conflict. [...]
>
> I think we should make sure that this conflict results in an error [...]

Agree - I've implemented this check.

**Comment by beyhan** [comment]
> > > And another topic to discuss is the usage of non-Ascii characters. [...]
> > 
> > 
> > I would suggest that the CC validates this and returns an error if it is not the case. [...]
> 
> Okay, I've implemented the **MUST** requirement for service binding names. But what about the **SHOULD** requirement for binding entry file names?
> 
> We would already violate this by using the defined `VCAP_SERVICES` attributes as file names, e.g. `binding_guid`, as the underscore is not allowed by the k8s spec. Should we:
> 
> 1. translate underscores to dashes (e.g. `binding_guid` to `binding-guid`) and then strictly enforce the k8s spec?
> 2. add the underscore to the list of allowed characters and enforce this slightly modified spec?
> 3. simply ignore this **SHOULD** requirement...
> 
> I would prefer one of the first two options.

Hi @philippthun,

I would say that we should go with option 1. because we aim to reuse existing tooling from the CNCF community here and it could be that they fail if we aren't conform with the K8s spe. 

@ameowlia , @ChrisMcGowan , @rkoster , @stephanme, @Gerg any opinion on this?

**Comment by beyhan** [comment]
I opened https://github.com/cloudfoundry/community/pull/1008 to address all this discussions.

**Comment by ameowlia** [comment]
👋  Hi @philippthun, I am in the middle of doing acceptance for the diego PRs for file-based service binding info.

❓  Are there docs on how to enable file-based service binding info for apps?

I looked through...
* The description in the PRs for diego and capi
* [The RFC](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0030-add-support-for-file-based-service-binding.md)
* [This technical specification doc](https://github.com/cloudfoundry/cloud_controller_ng/issues/4036)

...and I can't seem to find it.

**Comment by beyhan** [comment]
Hi @ameowlia,

in the RFC it is specified in https://github.com/cloudfoundry/community/blob/55a5ff9eca0f5c4fa21da61b37cf91f0a42e4355/toc/rfc/rfc-0030-add-support-for-file-based-service-binding.md?plain=1#L50-L51 and possible manifest implementation in https://github.com/cloudfoundry/community/blob/55a5ff9eca0f5c4fa21da61b37cf91f0a42e4355/toc/rfc/rfc-0030-add-support-for-file-based-service-binding.md?plain=1#L107-L113.

Looking into the implementation in https://github.com/cloudfoundry/cloud_controller_ng/pull/3997 the feature flag has the name as defined in the RFC `file-based-service-bindings` and it should be possible to activate it via https://v3-apidocs.cloudfoundry.org/version/3.182.0/index.html#update-an-app-feature for a given applications.

**Comment by philippthun** [comment]
@ameowlia - The release-candidate version of the docs has some info about this flag: https://v3-apidocs.cloudfoundry.org/version/release-candidate/#supported-app-features - actually only the name is interesting... As Beyhan already wrote, you have to enable it via the API.

Maybe you find [this repository](https://github.com/philippthun/sbf-tests) helpful - it contains test apps (and test descriptions) that I used for end-to-end validation of this feature. Our plan is to integrate this into CATS.

**Comment by ameowlia** [comment]
Thanks for those links @philippthun they really help! I was able to black box test the basic functionality today. I will continue reviewing tomorrow.

**Comment by ameowlia** [comment]
Hi @Dimitar Dimitrov & @plamendev,

The Diego PRs are failing [on linting in the pipeline](https://ci.funtime.lol/teams/wg-arp-diego/pipelines/diego-release/jobs/lint-repo/builds/426) because of "windows drift". [Here is the script that failed](https://github.com/cloudfoundry/wg-app-platform-runtime-ci/blob/main/diego-release/linters/check-for-windows-drift.bash). This happens when the rep windows job does not contain the same bosh properties as the rep (linux) job.

I don't see anything in the RFC about this only working on linux and not windows.

:question: Can you make new PRs to make this work with windows? Maybe also consider adding an acceptance test for windows.

**Comment by PlamenDoychev** [comment]
Hi @ameowlia i'll take a look at it. Unfortunately i am on a workshop today and will have availability tomorrow.

**Comment by klapkov** [comment]
Hello @ameowlia, 

I re-opened the PR's and created an acceptance test for windows diego cells. The drift has been resolved as well. Please let me know if any further changes are required. 

CATS:  https://github.com/cloudfoundry/cf-acceptance-tests/pull/1437
Diego: https://github.com/cloudfoundry/diego-release/pull/990
Rep: https://github.com/cloudfoundry/rep/pull/66
Executor: https://github.com/cloudfoundry/executor/pull/115

**Comment by beyhan** [comment]
I tried to make some of the existing CF clients aware of this feature:
https://github.com/pivotal-cf/java-cfenv/issues/296
https://github.com/cloudfoundry-community/go-cfenv/issues/28
https://github.com/cloudfoundry/cf-java-client/issues/1263
https://github.com/SAP/btp-environment-variable-access/pull/274 & https://github.com/SAP/btp-environment-variable-access/pull/273

Closing as this has been finished from CF side.
