### ISSUE TITLE
[RFC0027] Generic Per-Route Features

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/community#902]
This is a tracking issue for the implementation of https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0027-generic-per-route-features.md

```[tasklist]
### Tasks
- [ ] https://github.com/cloudfoundry/route-registrar/pull/40
- [ ] https://github.com/cloudfoundry/routing-release/pull/407
- [ ] https://github.com/cloudfoundry/routing-release/issues/421
```

**Comment by maxmoehl** [comment]
We already have https://github.com/cloudfoundry/route-registrar/pull/40 and https://github.com/cloudfoundry/routing-release/pull/407. Next up is gorouter. Would you prefer if we create issues for everything that needs to be done now to get a better overview? If so I could probably do that over the next few days.

**Comment by beyhan** [comment]
@maxmoehl I added the two mentioned PRs to the `tasks` list. Is it possible for you to add items to the list? If it is not much effort for you we would prefer to have a list with the the planed items.

**Comment by maxmoehl** [comment]
I think I would have to modify your initial issue description which I can't as I lack the permissions for this repo. At least the [docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists) only mention updating the list directly to add tasks.

**Comment by beyhan** [comment]
if you can't modify this one you can create another issue and we can close this. Your own issue you should be able to modify and TOC members also.

**Comment by maxmoehl** [comment]
I've created #909, can you close this one @beyhan?

**Comment by beyhan** [comment]
Closing in favour of #909. Thank you @maxmoehl!
