### ISSUE TITLE
Tracking Issue: Migrate CF and CI/CD hosts for CF documentation

### ISSUE THREAD

**Issue by pspinrad** [cloudfoundry/community#927]
### Summary

The static site app for the CF Docs published at [docs.cloudfoundry.org](http://docs.cloudfoundry.org/) are currently built in [this Concourse](https://runway-ci.eng.vmware.com/teams/mapbu-docs/pipelines/cf-current?group=oss) and pushed to the CF host at apps.sc2-04-pcf1-system.oc.vmware.com as configured [here](https://github.com/pivotal-cf/concourse-scripts-docs/tree/master/cf-current/oss).

To do: change the pipeline config to run on the [BOSH Concourse](https://bosh.ci.cloudfoundry.org/) and push to the Anynines CF host, at https://api.de.a9s.eu.

### Tasks
- [x] Get user accounts and service account and cred's for Anynines CF host
- [x] Get user accounts and group for BOSH Concourse host
- [x] Get user accounts and group for BOSH Concourse host
- [x] Get user accounts and group for BOSH Concourse host

**Comment by pspinrad** [comment]
The CF docs and UAA API reference have been migrated.

- Build pipelines now run on https://bosh.ci.cloudfoundry.org aka “BOSH Concourse,” under the wg-docs group:
  - CF docs: osspipeline
  - UAA API ref: uaa-api pipeline
- CF host where Concourse pushes the apps is now https://api.de.a9s.eu, aka “Anynines CF,” which is where DNS now resolves the domain docs.cloudfoundry.org.
- Pipeline configurations come from the pipeline-2024 directory of the docs-concourse-scripts repo, but that repo mostly contains old, defunct pipelines that I’m gonna get rid of.

**Comment by beyhan** [comment]
Thanks @pspinrad for the great summary! Adding the pipeline links for reference (they didn't work above):
CF docs: oss [pipeline](https://bosh.ci.cloudfoundry.org/teams/wg-docs/pipelines/cf-current)
UAA API ref: uaa-api [ pipeline](https://bosh.ci.cloudfoundry.org/teams/wg-docs/pipelines/cf-current?group=uaa-api)
