### ISSUE TITLE
Tracking Issue: Migrate CF and CI/CD hosts for UAA API reference

### ISSUE THREAD

**Issue by pspinrad** [cloudfoundry/community#928]
The static site apps for the UAA API reference published at https://docs.cloudfoundry.org/api/uaa/version/77.11.0/index.html#overview are currently built in [this Concourse](https://runway-ci.eng.vmware.com/teams/mapbu-docs/pipelines/api-docs?group=uaa-api) and pushed to the CF host at apps.sc2-04-pcf1-system.oc.vmware.com as configured [here](https://github.com/pivotal-cf/concourse-scripts-docs/tree/master/api-docs/uaa-api).

To do: change the pipeline config to run on the [BOSH Concourse](https://bosh.ci.cloudfoundry.org/) and push to the Anynines CF host, at https://api.de.a9s.eu.

Also, determine build / host infrastructure for CredHub API reference at https://docs.cloudfoundry.org/api/credhub/version/main/ and migrate if needed.

### Tasks
- [x] Get user accounts and service account and cred's for Anynines CF host
- [x] Get user accounts and group for BOSH Concourse host
- [x] Modify existing UAA API ref docs to push docs to A9s CF host
- [x] Modify existing UAA API ref docs to run on BOSH Concourse

**Comment by pspinrad** [comment]
@peterhaochen47

**Comment by peterhaochen47** [comment]
@pspinrad This is done now right? I see the app in the new cf instance now.

**Comment by pspinrad** [comment]
The CF docs and UAA API reference have been migrated.

- Build pipelines now run on https://bosh.ci.cloudfoundry.org aka “BOSH Concourse,” under the wg-docs group:
  - CF docs: osspipeline
  - UAA API ref: uaa-api pipeline
- CF host where Concourse pushes the apps is now https://api.de.a9s.eu, aka “Anynines CF,” which is where DNS now resolves the domain docs.cloudfoundry.org.
- Pipeline configurations come from the pipeline-2024 directory of the docs-concourse-scripts repo, but that repo mostly contains old, defunct pipelines that I’m gonna get rid of.

**Comment by beyhan** [comment]
Thanks @pspinrad for the great summary! Adding the pipeline links for reference (they didn't work above):
CF docs: oss [pipeline](https://bosh.ci.cloudfoundry.org/teams/wg-docs/pipelines/cf-current)
UAA API ref: uaa-api [pipeline](https://bosh.ci.cloudfoundry.org/teams/wg-docs/pipelines/cf-current?group=uaa-api)
